name: Fetch EPG

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  fetch_epg_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to reset it later

      - name: Download EPG file
        run: |
          curl -fSL "${{ secrets.EPG_URL }}" -o epg.xml

      - name: Log the downloaded file details
        run: |
          if [ -f "epg.xml" ]; then
            echo "EPG file downloaded successfully."
            ls -lh epg.xml
          else
            echo "Failed to download the EPG file."
          fi

      - name: Commit and force push without saving history
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"

          # Clear the commit history by resetting to the first commit
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          git reset --soft $FIRST_COMMIT

          # Stage and commit the changes
          git add epg.xml
          git commit -m "Update EPG file" || echo "No changes to commit"

          # Force push to overwrite history in the remote repository
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
